apiVersion: v1
kind: ServiceAccount
metadata:
  name: inferadb-control
  namespace: inferadb
  labels:
    app.kubernetes.io/name: inferadb-control
    app.kubernetes.io/component: control
    app.kubernetes.io/part-of: inferadb
