# Markdownlint configuration for deploy documentation
# Line length is relaxed for tables, code blocks, and URLs

MD013:
  # Disable line length for this technical document
  # Tables and code blocks naturally exceed 80 chars
  line_length: 120
  # Don't check inside code blocks
  code_blocks: false
  # Don't check tables
  tables: false
  # Don't check headings
  headings: false
