# StatefulSet for InferaDB Ledger
# Provides stable network identities and persistent storage for Raft consensus.
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: inferadb-ledger
  namespace: inferadb
  labels:
    app.kubernetes.io/name: inferadb-ledger
    app.kubernetes.io/instance: inferadb-ledger
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: ledger
    app.kubernetes.io/part-of: inferadb
    app.kubernetes.io/managed-by: flux
spec:
  serviceName: inferadb-ledger # Must match headless service name
  replicas: 3
  podManagementPolicy: Parallel # Start all pods simultaneously for faster bootstrap
  selector:
    matchLabels:
      app.kubernetes.io/name: inferadb-ledger
      app.kubernetes.io/component: ledger
  template:
    metadata:
      labels:
        app.kubernetes.io/name: inferadb-ledger
        app.kubernetes.io/instance: inferadb-ledger
        app.kubernetes.io/version: latest
        app.kubernetes.io/component: ledger
        app.kubernetes.io/part-of: inferadb
        app.kubernetes.io/managed-by: flux
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: ledger
          image: inferadb/ledger:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: grpc
              containerPort: 50051
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          envFrom:
            - configMapRef:
                name: inferadb-ledger-config
          volumeMounts:
            - name: data
              mountPath: /var/lib/ledger
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "2"
              memory: "4Gi"
          # Startup probe: allow time for Raft bootstrap
          startupProbe:
            grpc:
              port: 50051
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 24 # 2 minutes total
          # Liveness probe: detect hung processes
          livenessProbe:
            grpc:
              port: 50051
            initialDelaySeconds: 0
            periodSeconds: 10
            failureThreshold: 3
          # Readiness probe: only route traffic to healthy nodes
          readinessProbe:
            grpc:
              port: 50051
            initialDelaySeconds: 0
            periodSeconds: 5
            failureThreshold: 2
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app.kubernetes.io/name: inferadb-ledger
          app.kubernetes.io/component: storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
        # storageClassName will use cluster default if not specified
