# FoundationDB Cluster - Development Configuration
# ================================================
# Minimal single-replica FDB cluster for local development.
# NOT suitable for production use.
#
# Prerequisites:
# - FDB Kubernetes Operator must be installed
#
# Usage:
# kubectl apply -k flux/apps/base/foundationdb
---
apiVersion: apps.foundationdb.org/v1beta2
kind: FoundationDBCluster
metadata:
  name: inferadb-fdb
  namespace: inferadb
  labels:
    app.kubernetes.io/name: foundationdb
    app.kubernetes.io/instance: inferadb-fdb
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: inferadb
spec:
  version: 7.3.43

  # Minimal process counts for dev
  processCounts:
    storage: 1
    log: 1
    stateless: 1
    cluster_controller: 1

  # Database configuration - single copy for dev
  databaseConfiguration:
    redundancy_mode: single
    storage_engine: ssd-2
    usable_regions: 1

  # Fault domain - all in same zone for dev
  faultDomain:
    key: foundationdb.org/fdb-zone-id
    valueFrom: spec.nodeName

  # Routing configuration
  routing:
    publicIPSource: pod

  # Pod template for all FDB processes
  processes:
    general:
      podTemplate:
        spec:
          # Init container to fix volume permissions for local-path-provisioner
          # (which doesn't support fsGroup properly on Talos)
          initContainers:
            - name: fix-permissions
              image: busybox:1.36
              command: ["sh", "-c", "chown -R 4059:4059 /var/fdb/data"]
              securityContext:
                runAsUser: 0
              volumeMounts:
                - name: data
                  mountPath: /var/fdb/data

          containers:
            - name: foundationdb
              resources:
                requests:
                  cpu: 100m
                  memory: 256Mi
                limits:
                  cpu: 500m
                  memory: 512Mi
              securityContext:
                runAsUser: 4059
                runAsGroup: 4059
                readOnlyRootFilesystem: false

      # Persistent storage for FDB data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi

  # Sidecar container settings
  sidecarContainer:
    enableLivenessProbe: true
    enableReadinessProbe: true

  # Automation configuration
  automationOptions:
    deletionMode: All
    removalMode: All
---
# Service for FDB client connections
# FDB server binds to 4501 (offset of 4499 + 2*processNumber, where processNumber starts at 1)
apiVersion: v1
kind: Service
metadata:
  name: inferadb-fdb
  namespace: inferadb
  labels:
    app.kubernetes.io/name: foundationdb
    app.kubernetes.io/instance: inferadb-fdb
spec:
  selector:
    foundationdb.org/fdb-cluster-name: inferadb-fdb
  ports:
    - name: fdb
      port: 4500
      targetPort: 4501
      protocol: TCP
  type: ClusterIP
---
# ConfigMap with FDB cluster file (will be populated by operator)
apiVersion: v1
kind: ConfigMap
metadata:
  name: foundationdb-cluster-file
  namespace: inferadb
  labels:
    app.kubernetes.io/name: foundationdb
    app.kubernetes.io/instance: inferadb-fdb
data:
  # Placeholder - operator will update this with actual cluster connection string
  fdb.cluster: "inferadb:inferadb@inferadb-fdb:4500"
