---
apiVersion: v1
kind: Namespace
metadata:
  name: inferadb
  labels:
    # Pod Security Admission - restricted profile for application workloads
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
