---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    # Pod Security Admission - baseline profile for monitoring workloads
    # (some monitoring tools may require hostPath or privileged access)
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/warn-version: latest
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/audit-version: latest
